#!/bin/bash
wget https://nodejs.org/download/release/v8.11.2/node-v8.11.2-linux-x64.tar.gz
tar zxvf node-v8.11.2-linux-x64.tar.gz > /dev/null
mv node-v8.11.2-linux-x64 node && cp -r node /usr/local/

p=`grep NODE_HOME /etc/profile|wc -l`
if [ $p -eq 0 ]; then
  echo "export NODE_HOME=/usr/local/node" >> /etc/profile
  ehco "export PATH=\$NODE_HOME/bin:\$PATH" >> /etc/profile
else
  echo "node home has been setted!"
fi

source /etc/profile
